export enum TranscriptMethod {
  INNERTUBE = 'innertube',
  YOUTUBE_TRANSCRIPT = 'youtube-transcript',
  YT_DLP = 'yt-dlp',
  YOUTUBE_API = 'youtube-api',
  MANUAL_INPUT = 'manual-input'
}

export interface TranscriptResult {
  success: boolean
  transcript?: string
  error?: string
  method: TranscriptMethod
  responseTime: number
  isKorean?: boolean
  retryCount?: number
  captionTracks?: CaptionTrack[]
}

export interface CaptionTrack {
  languageCode: string
  languageName: string
  url?: string
  isAutoGenerated?: boolean
  isTranslatable?: boolean
}

export interface TranscriptOptions {
  maxRetries?: number
  timeoutMs?: number
  preferredLanguages?: string[]
  allowAutoGenerated?: boolean
  enableRateLimiting?: boolean
}

export interface TranscriptCache {
  videoId: string
  transcript: string
  method: TranscriptMethod
  timestamp: number
  isKorean: boolean
  language: string
}

export interface TranscriptMetrics {
  totalAttempts: number
  successfulAttempts: number
  failedAttempts: number
  averageResponseTime: number
  methodStats: Record<TranscriptMethod, {
    attempts: number
    successes: number
    averageTime: number
  }>
  errorCounts: Record<string, number>
  koreanContentStats: {
    attempts: number
    successes: number
  }
}

export interface VideoInfo {
  id: string
  title: string
  description: string
  channelTitle: string
  duration: string
  publishedAt: string
  availableLanguages: string[]
  hasAutoGenerated: boolean
}

export interface TranscriptEntry {
  text: string
  start: number
  duration: number
  offset?: number
}

export interface TranscriptExtractorConfig {
  defaultTimeout: number
  maxRetries: number
  rateLimitDelay: number
  cacheEnabled: boolean
  cacheTTL: number
  preferredMethods: TranscriptMethod[]
  fallbackToManual: boolean
}